spring:
  cloud:
    config:
      uri:
        - http://localhost:8888
        - http://config:8888
      name: news-service
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans,httptrace, busrefresh
