version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

    networks:
      - stockey-overlay

networks:
  stockey-overlay:
    external: true