eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone:
                - http://15.164.240.191:8083/eureka
                - http://15.164.240.191:8082/eureka
spring:
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
