
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: apigateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true



      routes:
        # auth
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/auth/logout
            - Path=/auth/nickname
          filters:
            - AuthorizationHeaderFilter

        # - id: member-service
        #   uri: lb://member-service
        #   predicates:

        #   filters:
        #     - AuthorizationHeaderFilter



        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/auth/**

        # member
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/nickname
            - Method=GET

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member
            - Path=/member/nickname
          filters:
            - AuthorizationHeaderFilter

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**


        # lab
        - id: laboratory-service
          uri: lb://LABORATORY-SERVICE
          predicates:
            - Path=/lab/**
          filters:
            - RewritePath=/lab/(?<segment>.*), /$\{segment}




jwt:
  # base64? ???? ?? ?, HS512? ??? ??? ???, 512??(64???) ??? ??? ???. ?? ????
  secretKey: '{cipher}10d6a9ef3db134316645ec176d42327e9055a5b380dcbe81a2662924b154fcb38774a7be9ac48ff17d91d512a297b79dbf5f39f0e7dd318c2a23b442fefb6202f798c269c52c21e85ab9a3a1d9854014'
  access:
    expiration: 100
  refresh:
    expiration: 14400
