eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://host.docker.internal:8761/eureka
spring:
    rabbitmq:
        host: 10.0.2.126
        port: 5672
        username: guest
        password: guest
