eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://discovery-service/eureka
spring:
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
