spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: "redis-container"
    password: "{cipher}7df8e06c3f6c837dd827ad35a8e961e5295a22fed3a2ac061a95f450ff71b991"
