eureka:
  instance:
    hostname: localhost

server:
  port: 0

spring:
  application:
    name: keyword-service


# springdoc swagger
springdoc:
  api-docs:
    path: /docs # ?? path ??
  swagger-ui:
    path: /swagger-ui # ?? path ??


django:
  url: localhost
  port: 8000

